### ISSUE TITLE
How can I setOnClickListen or setLongClickListen in span text?

### ISSUE THREAD

**Issue by NicodeLee** [lawloretienne/SpannableTextView#1]
Thanks !

**Comment by lawloretienne** [comment]
You need to set a ClickableSpan.  At the moment, I don't yet have support for that kind of span but looking to include it in the future.

**Comment by lawloretienne** [comment]
@rizhilee There is now support for a ClickableSpan.  Check out MainActivityFragment.java .  At the end there is an example.

**Comment by NicodeLee** [comment]
That's good. I see it
