### ISSUE TITLE
How to Remove Underline from Clickable Span

### ISSUE THREAD

**Issue by avtarsingh1122** [lawloretienne/SpannableTextView#7]
I am creating a new clickable span, and it automatically shows underline.
I tried using "isUnderline(false)" but its still showing underline.

How can I remove it ?

**Comment by lawloretienne** [comment]
You just need to override the `updateDrawState()` method of the `ClickableSpan` that you define.  Check out the accepted answer here :
http://stackoverflow.com/questions/16007147/how-to-get-rid-of-the-underline-in-a-spannable-string-with-a-clickable-object
